### ISSUE TITLE
How do I set up the SAIC/MQTT gateway correctly? I use EVCC and Mosquitto as MQTT brokers

### ISSUE THREAD

**Issue by fuxx1977** [SAIC-iSmart-API/saic-python-mqtt-gateway#106]
Hello,
Unfortunately, I am not receiving any data in the EVCC, such as the charge level of the MG4. I have set up the iSMART app correctly. I can read out the charge level or temperature there.
Unfortunately, I do not receive any data in the EVCC. When I make a query "evcc vehicle", I get the following answer.

I am not a developer, thank you in advance.
Best regards, Stefan

![2023-11-05 14_00_17-192 168 178 5 - Remotedesktopverbindung](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/105074671/a5ed0777-7a96-4cbe-a6c0-6d3408063af2)

**Comment by cybersmart-eu** [comment]
@fuxx1977 could you send your issue in english language please as this is a global community here.

Expecting a „click instruction“ I also consider a bit demanding - this is an open source project with some focus on IT enthusiasts I‘d say and ghey do a great job already but I wouldn‘t expect them to write instructions for „everyone“.

**Comment by tosate** [comment]
I don't know what EVCC is, but I have found this [issue](https://github.com/evcc-io/evcc/discussions/5142).

It seems like your EVCC installation expects data updates every 10 seconds. Otherwise it shows a timeout error for a specific topic. You need to find out how to configure the timeout value. I would suggest a large value like 24 hours.

**Comment by Tonno87** [comment]
@fuxx1977 Do you need help anymore?

**Comment by fuxx1977** [comment]
@sfudeus Hello, that would be great. Yes, the problem still exists. It would be great if you had a click guide or a good checklist for me. German is easier, but we can also write in English. Thank you in advance.

**Comment by Tonno87** [comment]
You should remove your timeout and set the poll mode to connected with an Intervall of 1m.

Otherwise it's not possible to detect your car without a manual wake:

![Screenshot_20240202-205936.png](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/59800400/97ef1ab9-fa2f-47eb-86cd-f8936835fc2f)

This is helpfully to detect the heater e.g.

Evcc polls your data every 1m without waking your car. This will end in a error message (outdated) but you can ignore it :)

If you want more config tweaks you can pm me on the goingelectric forum.

**Comment by Tonno87** [comment]
@fuxx1977 German Howto: [EVCC](https://github.com/SAIC-iSmart-API/saic-home-assistant-addon/wiki/EVCC-Tipps)
