### ISSUE TITLE
Tyre pressure same across all tyres

### ISSUE THREAD

**Issue by MelchMwoan** [SAIC-iSmart-API/saic-python-mqtt-gateway#251]
Good afternoon,
I have integrated the python mqtt gateway in Home Assistant for my Marvel R. But it looks like all 4 tyres are reporting the same pressure which I highly doubt is true. And the pressure is changing quite often between 2.2 and 2.6 bar.

![image](https://github.com/user-attachments/assets/047cb0da-4f39-4d8c-9a10-3222a35c5db8)

Is this expected behaviour?

**Comment by nanomad** [comment]
That depends on what the API reports back to us. For an MG4, during driving, the values change quite realistically

![image](https://github.com/user-attachments/assets/3f32b9e8-ed26-42c1-805e-3de35a8338cb)

It may be the Marvel R TBox supplies an average value across 4 tyres instead of individual readings (I also see you are lacking one decimal digit of precision)

**Comment by MelchMwoan** [comment]
![image](https://github.com/user-attachments/assets/785722e0-5d28-4f99-acc9-b894e86c1cff)
It looks like it does work properly during driving, it is only when the car is idle the weird fluctuation and equal tyre pressures occurs.

**Comment by nanomad** [comment]
That's normal, sensors are not battery powered but they are motion
activated/powered. When the car is stationary the tbox reports the last
reading

Il Mar 30 Lug 2024, 11:08 MelchMwoan ***@***.***> ha scritto:
