### ISSUE TITLE
[0.3.0 rc1] Confusing setting name 'refresh_period_after_shutdown'

### ISSUE THREAD

**Issue by nanomad** [SAIC-iSmart-API/saic-python-mqtt-gateway#33]
So, looking at this variable name I would expect it to work like `refresh_period_active` or `refresh_period_inactive`, i.e. how often to poll the car after a shutdown but before being marked as inactive. Instead it works as a deadline, basically treating the car as active and polling every `refresh_period_active` seconds.

I would propose to:
- Use `refresh_period_after_shutdown` as a proper refresh period, defaulting it to `refresh_period_active` so that users can customize it (i.e. I myself would probably check every 2 to 5 minutes since I rarely DC fast charge to avoid stressing the LV battery)
- Implement a `refresh_period_inactive_grace` setting that works as the current `refresh_period_after_shutdown`

I'm going to implement those changes on my fork, if you think they can be useful I'll open a PR

**Comment by tosate** [comment]
Hi @nanomad 

- `refresh_period_active` defines in which intervals the polling occurs if the high-voltage battery is active (engine running or charging)
- `refresh_period_inactive` defines in which intervals the polling occurs if the high-voltage battery is inactive (engine off and no charging)

Since there is only a notification when the motor starts, but no notification when charging starts, the gateway never detects when the start charging event. Since many people stop their car and then connect it immediately to a charger, it would be useful to extend the polling for a while after the engine is turned off. This increases the probability to detect the charging.
`refresh_period_after_shutdown` defines how long the polling continues after the shutdown (10 minutes by default). This extended polling occurs with the same frequency as the active mode (`refresh_period_active`). Since it does not define a periodic cycle, but rather a time window a better name might be `refresh_window_after_shutdown`.

I took this over from the Java version with the same variable names, since I think that the basic idea is very good. If I get you right, you would prefer to do the polling after shutdown less frequently and therefore you want to introduce a third period. Of course this requires also a limit for the time window and that would be defined in `refresh_period_inactive_grace`.

You could do that. However, after testing a week I think that the continuation with the `refresh_period_active` works quite well. Configuring two variables instead of one adds additional complexity and requires that the user understands in detail how it works. On the other hand, it provides more flexibility.
