### ISSUE TITLE
Minor documentation issue with force vs forced

### ISSUE THREAD

**Issue by paulhomes** [SAIC-iSmart-API/saic-python-mqtt-gateway#44]
I read the documentation in README.md for using MQTT topic saic/<saic_user>/vehicles/<vehicle_id>/refresh/mode/set to force a refresh. The Value Range column has "periodic/off/force" but the Description column has "(value: forced)" so I wasn't sure whether to use force or forced. I initially tried forced but got an Unsupported payload error so switched to force which worked.

Can I suggest changing "(value: forced)" to "(value: force)"

**Comment by tosate** [comment]
Speaking about documentation, could someone explain me the difference between all of those front air blowing modes?

- frontWindowDefrosterHeating: blowing hot air to the front window to defrost
- remoteClimateState front: ???
- remoteClimateState blowingOnly: ???

I know the first one for defrosting the front window in winter. But what are the other two? Is it with and without A/C?

**Comment by Ivesvdf** [comment]
Do we consider the naming inside HA as part of 0.3.0 part of this "documentation" as well? Currently the options are as follows
![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/264447/b2687c06-d188-45cd-b336-ff09a07a67ca)

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/264447/4561418e-6e29-40bb-8eb0-ed7a4689c51b)

where  it's less than obvious what each option does. 

For example: 
- if operation is auto and preset is off, does the system do nothing? And if so, then what is the point of having the operation choice? Preset off probably should not exist?
- What's the difference between Off and None (does None indicate unknown?)? 
- What does On mean, does it imply the current internal AC setting or just auto AC? 
- BlowingOnly possibly means A/C is disabled? So ventilation only.
- And front may mean defrost / defog front window??

**Comment by tosate** [comment]
The functionality is the same as in the iSMART app.

![4235C5FF-F61F-4982-A032-78E808D8D7E2_1_201_a](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/35031183/5d22d3fe-971f-47d0-882b-b5d1b7b0b29e)

- on: activate the A/C for heating or cooling (temperature can be selected)
- blowingOnly: A/C blowing mode (temperature cannot be selected) 
- front: defrost / dehumidify front window
- off: deactivate A/C or front defrost

I still don't know what the blowing mode is used for.

The modes mentioned above have been mapped to a (HA climate entity)[https://developers.home-assistant.io/docs/core/entity/climate/]

![image](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/assets/35031183/eeb2fc79-83bd-405b-bb42-ba874b3b968d)

This is usually a thermostat that can be switched on or off with the operation control. You can choose a temperature or select a preset entry.

Can you please help with this @nanomad?

- Would it be possible to map on/off to the operation control of the HA climate entity?
- Maybe the climate control should be limited to the A/C functionality without any presets. You can switch it on/off and select a temperature.
- blowingOnly and front defrost are just switches because they don't let you choose a temperature value

**Comment by tisoft** [comment]
blowingOnly switches the A/C off, but keeps the blower on. The image shows that setting when done while the cat is on. Why anyone would want to do that, I don’t know. 😂Am 26.07.2023 um 09:17 schrieb Thomas Salm ***@***.***>:﻿
The functionality is the same as in the iSMART app.


on: activate the A/C for heating or cooling (temperature can be selected)
blowingOnly: A/C blowing mode (temperature cannot be selected)
front: defrost / dehumidify front window
off: deactivate A/C or front defrost

I still don't know what the blowing mode is used for.
The modes mentioned above have been mapped to a (HA climate entity)[https://developers.home-assistant.io/docs/core/entity/climate/]

This is usually a thermostat that can be switched on or off with the operation control. You can choose a temperature or select a preset entry.
Can you please help with this @nanomad?

Would it be possible to map on/off to the operation control of the HA climate entity?
Maybe the climate control should be limited to the A/C functionality without any presets. You can switch it on/off and select a temperature.
blowingOnly and front defrost are just switches because they don't let you choose a temperature value

**Comment by tosate** [comment]
They call it A/C-blowing (at least in the German version) because it switches the A/C  off, but keeps the blower on? That's odd. Thank you @tisoft

**Comment by Ivesvdf** [comment]
> Would it be possible to map on/off to the operation control of the HA climate entity?
Maybe the climate control should be limited to the A/C functionality without any presets. You can switch it on/off and select a temperature.
blowingOnly and front defrost are just switches because they don't let you choose a temperature value

This makes sense to me. Maybe we should call on/off "auto"? Because that's essentially auto mode in A/C terminology. 

And then have the "auto thermostat", plus a switch for blowing only and a switch for Defog Front. 

`when auto enabled: 
  switch blowing only = off
  switch front = off

when blowing only enabled: 
  switch  auto = off 
  switch front = off 

when front enabled:
  switch auto = off
  switch blowing only = off
  `

**Comment by nanomad** [comment]
@tosate I think it can be done yeah, Internally they do set temps but I think we can ignore that for now.

**Comment by tosate** [comment]
Sounds good!

I didn't even know that you can remote control the heated seats. Maybe it's not available for my car.

**Comment by nanomad** [comment]
@tosate to avoid scope creep I'd suggest we postpone this new A/C control after 0.3.0.
